services: 
  db:
    image: postgres:13
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    tty: true
    stdin_open: true
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"  
volumes:
  bundle_cache:
  db_data: