services: 
  db:
    image: postgres:13
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: myapp_development
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - builde_data:/usr/local/bundle:cached
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_development
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_data:
  db_data: